apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: speculative-inference
spec:
  type: LoadBalancer
  selector:
    app: speculative-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000